In [1]:
import os
import pandas as pd
import numpy as np

In [40]:
os.makedirs("./results/processed_results", exist_ok=True)

In [47]:
files = os.listdir("./results")
files.sort()
exp_dict_to_df_array = dict()
for file in files:
    if ".csv" not in file: continue
    exp_prefix = "_".join(file.split("_")[:-1])
    df = pd.read_csv("results/" + file, index_col = 0)
    if exp_prefix not in exp_dict_to_df_array:
        exp_dict_to_df_array[exp_prefix] = []

    df.index = df.pop("name")
    exp_dict_to_df_array[exp_prefix].append(df.iloc[-15:, :]) ## I made a mistake in my DBMS EValuator class which is why all pandas dataframes are concatenated per experiment

In [48]:
exp_dict_to_df_array["mysql_col"][0]

,create,update_nodes,update_edges,delete,read_1,read_in_mem_1,read_2,read_in_mem_2,read_3,read_in_mem_3
name,,,,,,,,,,
PPI,86.004283,0.481804,1.597379,1.573835,16.220534,6.717750,112.849327,14.621667,522.413188,24.236242
1000_nodes_5_edges,3.255854,0.915062,0.308598,0.287664,7.322174,0.591032,14.052576,0.799277,37.227344,1.053764
1000_nodes_10_edges,4.036998,0.370258,0.124202,0.450024,8.683546,0.624501,34.738062,0.968983,67.099340,1.393142
1000_nodes_20_edges,4.990823,0.775834,0.222606,0.295913,11.464362,0.689317,54.509161,1.239263,98.903608,2.406261
1000_nodes_scale_free,2.195488,0.929412,0.328312,0.243681,1.681104,0.148348,3.339382,0.181378,7.216583,0.218751
10000_nodes_5_edges,9.706843,0.523855,0.278495,0.437646,7.357429,0.814008,14.226612,1.700453,39.622586,2.483775
10000_nodes_10_edges,17.094129,0.763552,0.220075,0.310473,8.869932,1.087922,36.711971,2.610101,91.913718,4.370028
10000_nodes_20_edges,25.745981,0.584832,0.190126,0.554479,11.422090,1.643894,61.126465,4.468120,537.884280,7.850947
10000_nodes_scale_free,6.319945,0.540086,0.440139,0.624128,2.028944,0.180652,8.739975,0.271546,30.264574,0.395106
100000_nodes_5_edges,63.309568,0.531131,0.289523,0.485001,7.462910,3.082012,14.579045,10.547388,37.393725,15.632322
100000_nodes_10_edges,141.387772,0.469376,0.247789,0.461013,9.066222,5.676087,36.591717,17.971215,97.054059,28.374082
100000_nodes_20_edges,568.207979,0.398410,2.006148,1.094794,11.810795,10.552178,60.320605,32.114926,792.019840,80.152773
100000_nodes_scale_free,38.977532,0.807909,0.612053,1.464482,1.862650,0.759017,22.895289,1.735917,125.383114,2.408715
1000000_nodes_5_edges,2994.697405,0.599883,5.267841,2.268919,7.709505,26.469382,15.634815,99.728620,39.918568,151.509284
1000000_nodes_scale_free,426.576001,0.602074,6.487584,2.059821,1.885477,4.156542,84.934192,7.941395,814.919268,13.636563

In [49]:
for exp_prefix in exp_dict_to_df_array:
    # if "neo4j" in exp_prefix: continue
    print(exp_prefix)
    mean_df = pd.DataFrame(np.mean(exp_dict_to_df_array[exp_prefix], axis = 0), index = exp_dict_to_df_array[exp_prefix][0].index, columns = exp_dict_to_df_array[exp_prefix][0].columns)
    std_df = pd.DataFrame(np.std(exp_dict_to_df_array[exp_prefix], axis = 0), index = exp_dict_to_df_array[exp_prefix][0].index, columns = exp_dict_to_df_array[exp_prefix][0].columns)
    mean_df["name"] = mean_df.index
    mean_df = mean_df.reset_index(drop = True)
    std_df["name"] = std_df.index
    std_df = std_df.reset_index(drop = True)
    mean_df.to_csv(f"./results/processed_results/{exp_prefix}_mean.csv")
    std_df.to_csv(f"./results/processed_results/{exp_prefix}_std.csv")

mysql_col
mysql_mysql_list
neo4j_col
neo4j_neo4j_list
postgres_col
postgres_postgres_list

In [17]:
exp_dict_to_df_array["mysql_col"][1]

,name,create,update_nodes,update_edges,delete,read_1,read_in_mem_1,read_2,read_in_mem_2,read_3,read_in_mem_3
0,PPI,83.162242,0.466931,1.419537,2.433333,16.599740,6.754693,139.194719,15.705988,564.465107,24.479023
1,1000_nodes_5_edges,3.316783,0.533082,0.329302,0.623349,7.573082,0.591881,14.367195,0.798990,45.096620,1.070303
2,1000_nodes_10_edges,3.979122,0.521975,0.186084,0.276981,9.087307,0.620936,35.456096,0.955593,95.593959,1.576331
3,1000_nodes_20_edges,5.428254,0.851278,0.216280,0.271408,11.678975,0.678072,67.710022,1.247948,156.545301,3.136289
4,1000_nodes_scale_free,2.161783,0.502802,0.375040,0.781622,1.813203,0.151383,3.536793,0.187480,7.714407,0.233217
5,10000_nodes_5_edges,9.887756,0.534259,0.298365,0.721307,7.477900,0.812800,14.557416,1.685375,48.105517,2.488769
6,10000_nodes_10_edges,16.458274,1.068620,0.294071,0.291777,9.020739,1.074073,37.244967,2.574743,144.001896,5.516575
7,10000_nodes_20_edges,26.870774,0.708111,0.224162,0.446813,11.687543,1.630411,76.998677,4.605839,511.196087,7.799989
8,10000_nodes_scale_free,6.665712,0.516077,0.216151,0.305622,2.189817,0.186029,9.093998,0.291597,30.990161,0.414319
9,100000_nodes_5_edges,64.026875,0.546216,0.298111,0.660441,7.636169,3.052559,14.702554,10.512354,48.014112,15.640751
10,100000_nodes_10_edges,135.669130,0.575234,0.274518,0.387019,9.328731,5.596125,37.193624,18.015945,152.936290,36.487290
11,100000_nodes_20_edges,654.761418,0.363664,1.622184,1.375062,12.104824,10.548293,76.349921,33.406713,730.387591,53.974486
12,100000_nodes_scale_free,37.269961,0.998361,0.554360,0.927839,2.054545,0.865353,24.493267,1.977437,126.288538,2.250398
13,1000000_nodes_5_edges,2995.528965,0.581188,5.713060,2.132452,7.921251,26.459558,15.917217,100.995167,50.698177,158.237360
14,1000000_nodes_scale_free,429.441334,0.385515,5.767300,2.445243,2.173585,6.251570,91.567804,9.438938,833.866675,14.018094

In [18]:
exp_dict_to_df_array["mysql_col"][2]

,name,create,update_nodes,update_edges,delete,read_1,read_in_mem_1,read_2,read_in_mem_2,read_3,read_in_mem_3
15,PPI,84.813638,0.458628,1.964532,0.468382,16.470126,6.600137,138.718298,15.608328,536.131751,24.220125
16,1000_nodes_5_edges,3.357113,0.941699,0.310229,0.890598,7.544838,0.584355,14.620615,0.789245,45.753121,1.046960
17,1000_nodes_10_edges,4.236125,0.512666,0.194746,0.543406,8.936808,0.612884,35.415040,0.953587,95.617093,1.558024
18,1000_nodes_20_edges,5.046534,1.108009,0.702448,0.256536,11.772646,0.678220,67.691134,1.238586,156.849396,3.077779
19,1000_nodes_scale_free,2.237149,0.569937,0.692723,0.454243,1.805138,0.149528,3.520816,0.185019,7.666432,0.229880
20,10000_nodes_5_edges,10.041555,0.525936,0.403853,0.630869,7.507021,0.812125,14.598591,1.692981,48.157504,2.478396
21,10000_nodes_10_edges,17.362135,0.513473,0.215094,0.633468,8.971610,1.067615,36.994456,2.588469,143.558154,5.487863
22,10000_nodes_20_edges,26.918272,0.319624,0.132277,0.268931,11.800143,1.612862,76.965250,4.568580,516.309978,7.753676
23,10000_nodes_scale_free,6.082366,0.711045,0.210681,0.312072,2.172258,0.183683,9.088551,0.282657,30.808915,0.407951
24,100000_nodes_5_edges,63.187636,0.523502,0.242938,0.586154,7.682389,3.087353,14.786180,10.580802,48.048629,15.745519
25,100000_nodes_10_edges,139.369709,0.473127,0.237682,0.482785,9.314286,5.548089,37.265465,18.008434,151.743335,36.467665
26,100000_nodes_20_edges,656.148206,0.306353,1.754146,0.857216,12.184416,10.493284,76.382970,33.354237,784.980843,63.653159
27,100000_nodes_scale_free,40.653586,0.781936,0.857532,0.870749,2.041683,0.844535,24.287903,1.299923,126.768789,2.060786
28,1000000_nodes_5_edges,3020.720039,0.861356,3.986884,0.916209,7.974157,26.262989,15.986310,99.251054,50.432141,153.046615
29,1000000_nodes_scale_free,427.050519,0.568729,5.341841,2.364413,2.155918,5.983213,90.804161,9.548729,833.461883,14.911876