In [2]:
import pandas as pd
import os
import numpy as np

In [3]:
output_dir = "results/processed_results_memory"
os.makedirs(output_dir, exist_ok = True)

In [4]:
memory_data = pd.read_csv("memory_usage_log.csv")

In [29]:
import pandas as pd
import numpy as np
import re

def memory_data_to_csv(memory_data, group_fun="mean"):
    expanded = memory_data["function_name"].str.split("__", expand=True)
    
    df = memory_data.copy()
    df["engine"] = expanded[0] + "_" + expanded[1]
    
    def transform_name(val):
        parts = val.split("_")
        if len(parts) != 2:
            return val
            
        first, second = parts[0], parts[1]
        
        if first.isdigit():
            first = f"{first}_nodes"
            
        if second == "SF":
            second = "scale_free"
        elif second.isdigit():
            second = f"{second}_edges"
            
        return f"{first}_{second}"

    df["name"] = expanded[2].apply(transform_name)
    df["operation"] = expanded[3]
    
    unique_engines = df["engine"].unique()
    dfs_by_engine = {}
    
    def natural_sort_key(s):
        return [int(text) if text.isdigit() else text.lower()
                for text in re.split('([0-9]+)', s)]

    for engine in unique_engines:
        subset = df[df["engine"] == engine]
        
        pivot_df = subset.pivot_table(
            index="name", 
            columns="operation", 
            values="peak_memory_mb",
            aggfunc=group_fun
        ).reset_index()
        
        pivot_df.columns.name = None
        
        pivot_df["sort_key"] = pivot_df["name"].apply(natural_sort_key)
        
        pivot_df = pivot_df.sort_values("sort_key", ascending =False).drop(columns=["sort_key"]).reset_index(drop=True)
        
        dfs_by_engine[engine] = pivot_df
        pivot_df.to_csv(f"{output_dir}/{engine}_{group_fun}.csv", index=True)
        
    return dfs_by_engine

results_std = memory_data_to_csv(memory_data, "std")
results = memory_data_to_csv(memory_data, "mean")

In [30]:
results["mysql_col"]

,name,create,delete,read_1,read_2,read_3,update_edges,update_nodes
0,ppi,0.011570,0.004739,4.361297,15.052898,29.044954,18.721001,0.693287
1,1015074_nodes_SBC,0.007839,0.004799,15.496849,16.171529,16.168975,60.715431,15.496887
2,1000000_nodes_scale_free,0.007835,0.004774,15.266838,1624.534832,3345.093483,30.786842,15.266998
3,1000000_nodes_5_edges,0.007833,0.004836,15.266838,57.987717,58.608787,76.301994,15.266865
4,100000_nodes_scale_free,0.007834,0.004723,2.170762,123.487486,332.387249,2.965492,1.533955
5,100000_nodes_20_edges,0.007833,0.004761,5.837167,24.156835,53.991285,30.525627,1.533992
6,100000_nodes_10_edges,0.007833,0.004745,2.953603,11.862811,14.590886,15.266899,1.533960
7,100000_nodes_5_edges,0.007832,0.004704,1.533928,5.910200,6.291286,7.637444,1.533953
8,10000_nodes_scale_free,0.007833,0.004742,13.056888,341.043061,482.483970,0.281502,0.160672
9,10000_nodes_20_edges,0.007832,0.004772,0.866717,3.153029,288.517125,3.059807,0.160685
10,10000_nodes_10_edges,0.007832,0.004742,0.468529,1.426002,11.338828,1.533928,0.160664
11,10000_nodes_5_edges,0.007831,0.004723,0.264545,0.764272,1.009423,0.770988,0.160681
12,1000_nodes_scale_free,0.007856,0.004704,2.031248,5.918181,6.543701,0.058517,0.041967
13,1000_nodes_20_edges,0.007856,0.004707,0.178189,1.916343,9.935711,0.313225,0.042044
14,1000_nodes_10_edges,0.007852,0.004742,0.115904,0.612469,5.024567,0.160637,0.042024
15,1000_nodes_5_edges,0.007852,0.004741,0.089701,0.205416,0.822262,0.084343,0.042087

In [21]:
results_std["mysql_col"]

,name,create,delete,read_1,read_2,read_3,update_edges,update_nodes
0,1000000_nodes_5_edges,0.000000,0.000250,0.000000,0.002038,0.001307,0.000000,0.000061
1,1000000_nodes_scale_free,0.000000,0.000000,0.000000,0.000654,0.000364,0.000000,0.000000
2,100000_nodes_10_edges,0.000000,0.000143,0.003504,0.001745,0.000962,0.000335,0.000065
3,100000_nodes_20_edges,0.000000,0.000140,0.002020,0.001051,0.003190,0.000000,0.000080
4,100000_nodes_5_edges,0.000000,0.000032,0.000000,0.001023,0.002950,0.000000,0.000058
5,100000_nodes_scale_free,0.000000,0.000106,0.000462,0.000096,0.000970,0.000000,0.000061
6,10000_nodes_10_edges,0.000000,0.000142,0.000405,0.001340,0.000536,0.000000,0.000061
7,10000_nodes_20_edges,0.000000,0.000168,0.003108,0.000426,0.005574,0.000000,0.000075
8,10000_nodes_5_edges,0.000000,0.000105,0.005978,0.001681,0.004071,0.000000,0.000074
9,10000_nodes_scale_free,0.000000,0.000154,0.000430,0.001056,0.001627,0.000000,0.000068
10,1000_nodes_10_edges,0.000051,0.000153,0.007474,0.000523,0.002935,0.000000,0.000493
11,1000_nodes_20_edges,0.000053,0.000034,0.008107,0.003087,0.002989,0.000000,0.000494
12,1000_nodes_5_edges,0.000054,0.000153,0.000303,0.006604,0.001884,0.000000,0.000642
13,1000_nodes_scale_free,0.000048,0.000032,0.003008,0.000334,0.000422,0.000000,0.000396
14,1015074_nodes_SBC,0.000024,0.000226,0.000000,0.003048,0.002136,0.000335,0.000070
15,ppi,0.019887,0.000133,0.004987,0.000756,0.000858,0.000335,0.000061

In [20]:
dfs_by_engine

{'mysql_col': operation      create    delete     read_1       read_2       read_3  \
 dataset
 1000000_5    0.007833  0.004836  15.266838    57.987717    58.608787
 1000000_SF   0.007835  0.004774  15.266838  1624.534832  3345.093483
 100000_10    0.007833  0.004745   2.953603    11.862811    14.590886
 100000_20    0.007833  0.004761   5.837167    24.156835    53.991285
 100000_5     0.007832  0.004704   1.533928     5.910200     6.291286
 100000_SF    0.007834  0.004723   2.170762   123.487486   332.387249
 10000_10     0.007832  0.004742   0.468529     1.426002    11.338828
 10000_20     0.007832  0.004772   0.866717     3.153029   288.517125
 10000_5      0.007831  0.004723   0.264545     0.764272     1.009423
 10000_SF     0.007833  0.004742  13.056888   341.043061   482.483970
 1000_10      0.007852  0.004742   0.115904     0.612469     5.024567
 1000_20      0.007856  0.004707   0.178189     1.916343     9.935711
 1000_5       0.007852  0.004741   0.089701     0.205416     0.822262
 1000_SF      0.007856  0.004704   2.031248     5.918181     6.543701
 1015074_SBC  0.007839  0.004799  15.496849    16.171529    16.168975
 ppi          0.011570  0.004739   4.361297    15.052898    29.044954

 operation    update_edges  update_nodes
 dataset
 1000000_5       76.301994     15.266865
 1000000_SF      30.786842     15.266998
 100000_10       15.266899      1.533960
 100000_20       30.525627      1.533992
 100000_5         7.637444      1.533953
 100000_SF        2.965492      1.533955
 10000_10         1.533928      0.160664
 10000_20         3.059807      0.160685
 10000_5          0.770988      0.160681
 10000_SF         0.281502      0.160672
 1000_10          0.160637      0.042024
 1000_20          0.313225      0.042044
 1000_5           0.084343      0.042087
 1000_SF          0.058517      0.041967
 1015074_SBC     60.715431     15.496887
 ppi             18.721001      0.693287  ,
 'mysql_list': operation      create    delete     read_1       read_2       read_3  \
 dataset
 1000000_5    0.007925  0.004742  15.266838    57.985974    58.608271
 1000000_SF   0.007928  0.004857  15.266838  1624.530391  3345.091518
 100000_10    0.007849  0.004745   2.949203    11.863274    14.589892
 100000_20    0.007925  0.004770   5.839058    24.157195    53.990752
 100000_5     0.007860  0.004723   1.533928     5.909583     6.290691
 100000_SF    0.007927  0.004704   2.170253   123.487031   332.385441
 10000_10     0.007833  0.004707   0.460265     1.436221    11.338779
 10000_20     0.007833  0.004734   0.862721     3.152411   288.515004
 10000_5      0.007832  0.004704   0.262326     0.763710     1.006646
 10000_SF     0.007834  0.004704  13.054391   341.041262   482.482655
 1000_10      0.007851  0.004704   0.107982     0.610906     5.022521
 1000_20      0.007855  0.004713   0.173473     1.914664     9.939007
 1000_5       0.007855  0.004723   0.087749     0.204210     0.821329
 1000_SF      0.007869  0.004704   2.027569     5.917147     6.543049
 1015074_SBC  0.007840  0.004837  15.496849    16.168167    16.168009
 ppi          0.008003  0.004739   4.351376    15.051176    29.039945

 operation    update_edges  update_nodes
 dataset
 1000000_5       76.301994     15.266980
 1000000_SF      30.786842     15.266873
 100000_10       15.266899      1.533960
 100000_20       30.525627      1.534008
 100000_5         7.637444      1.534088
 100000_SF        2.965492      1.534088
 10000_10         1.533928      0.160669
 10000_20         3.059807      0.160685
 10000_5          0.770988      0.160664
 10000_SF         0.281502      0.160797
 1000_10          0.160637      0.040422
 1000_20          0.313225      0.040361
 1000_5           0.084343      0.040240
 1000_SF          0.058517      0.040778
 1015074_SBC     60.715431     15.497009
 ppi             18.720940      0.693287  ,
 'neo4jce_col': operation      create    delete     read_1       read_2       read_3  \
 dataset
 1000000_5    0.037273  0.026559  15.266838    57.987705    58.590396
 1000000_SF   0.037201  0.025628  15.266838  1915.079733  4016.453517
 100000_10    0.037654  0.029924   2.957953    11.846287    14.406683
 100000_20    0.037637  0.029934   5.849218    24.103302    68.460475
 100000_5     0.037667  0.029945   1.533928     5.911638     6.275564
 100000_SF    0.037592  0.029190   2.526905   144.223445   393.879497
 10000_10     0.038009  0.029758   0.470536     1.418485    11.147641
 10000_20     0.037992  0.029818   0.874239     3.110217   287.119184
 10000_5      0.037270  0.025418   0.269229     0.762473     1.007759
 10000_SF     0.037965  0.029799  12.864279   339.792137   480.629632
 1000_10      0.037401  0.026829   0.133673     0.722929     4.883211
 1000_20      0.038074  0.029779   0.195190     2.281674     9.733704
 1000_5       0.037626  0.025555   0.103197     0.240613     0.975566
 1000_SF      0.037271  0.024570   2.390791     5.759582     5.633145
 1015074_SBC  0.031432  0.028079  15.496849    16.006185    15.701698
 ppi          0.107755  0.030027   4.250594    19.820009    43.474380

 operation    update_edges  update_nodes
 dataset
 1000000_5       76.301994     15.266900
 1000000_SF      30.786842     15.266838
 100000_10       15.266838      1.534088
 100000_20       30.525627      1.534088
 100000_5         7.637444      1.534088
 100000_SF        2.965492      1.533928
 10000_10         1.533928      0.255997
 10000_20         3.059807      0.255988
 10000_5          0.770988      0.256006
 10000_SF         0.362588      0.253806
 1000_10          0.361388      0.249099
 1000_20          0.361812      0.249109
 1000_5           0.360369      0.249109
 1000_SF          0.356338      0.241562
 1015074_SBC     60.715370     15.496949
 ppi             18.720940      0.693420  ,
 'neo4jce_list': operation      create    delete     read_1       read_2        read_3  \
 dataset
 1000000_5    0.030796  0.016860  15.266838    58.137114     59.273314
 1000000_SF   0.030756  0.016475  15.266838  5911.049812  11876.726911
 100000_10    0.031329  0.019253   3.020478    12.361122     27.499242
 100000_20    0.031329  0.019253   5.947875    26.105822    207.612258
 100000_5     0.031327  0.019253   1.537115     6.065013      7.015546
 100000_SF    0.031195  0.019253   7.432724   448.078355   1227.364600
 10000_10     0.031204  0.019108   0.531456     2.152501     20.160850
 10000_20     0.030804  0.016973   0.981806     7.892467    287.875754
 10000_5      0.031219  0.019137   0.296678     0.914511      2.989268
 10000_SF     0.030766  0.017795  20.851440   340.541498    482.429646
 1000_10      0.030567  0.017322   0.271988     2.053295     12.488629
 1000_20      0.030897  0.018190   0.469095     6.901818     20.075735
 1000_5       0.030548  0.016579   0.173500     0.626560      2.794892
 1000_SF      0.030563  0.016242   6.971091    14.220259     14.145340
 1015074_SBC  0.031083  0.017746  15.496849    16.005313     15.711654
 ppi          0.029101  0.019137   4.807967    31.238968     58.106570

 operation    update_edges  update_nodes
 dataset
 1000000_5       76.301994     15.266885
 1000000_SF      30.786842     15.266838
 100000_10       15.266838      1.534088
 100000_20       30.525627      1.534088
 100000_5         7.637444      1.534088
 100000_SF        2.965492      1.533928
 10000_10         1.533928      0.252984
 10000_20         3.059807      0.252821
 10000_5          0.770988      0.252916
 10000_SF         0.362633      0.250793
 1000_10          0.361446      0.246096
 1000_20          0.361800      0.246085
 1000_5           0.360354      0.246067
 1000_SF          0.356338      0.237606
 1015074_SBC     60.715370     15.496938
 ppi             18.720940      0.693420  ,
 'neo4jee_col': operation      create    delete     read_1       read_2       read_3  \
 dataset
 1000000_5    0.036670  0.018643  15.266838    57.988028    58.590328
 1000000_SF   0.036678  0.018643  15.266838  1915.079741  4016.453346
 100000_10    0.036796  0.016688   2.962677    11.848267    14.402944
 100000_20    0.036670  0.018643   5.851412    24.105378    68.403888
 100000_5     0.036667  0.018614   1.533928     5.914560     6.278255
 100000_SF    0.036675  0.018556   2.526644   144.223794   393.879475
 10000_10     0.036427  0.015735   0.472935     1.412172    11.147551
 10000_20     0.036650  0.015869   0.872123     3.110025   287.119257
 10000_5      0.036939  0.018498   0.266375     0.764132     1.010793
 10000_SF     0.036581  0.015940  12.864589   339.791968   480.629699
 1000_10      0.036939  0.018468   0.136602     0.726982     4.883638
 1000_20      0.036939  0.018468   0.197737     2.284609     9.733866
 1000_5       0.036421  0.016152   0.097939     0.241867     0.973531
 1000_SF      0.036429  0.015616   2.390766     5.759807     5.633044
 1015074_SBC  0.030022  0.016127  15.496849    16.009185    15.707561
 ppi          0.045596  0.018643   4.253380    19.820358    43.474460

 operation    update_edges  update_nodes
 dataset
 1000000_5       76.301994     15.266998
 1000000_SF      30.786842     15.266838
 100000_10       15.266838      1.534061
 100000_20       30.525627      1.534088
 100000_5         7.637444      1.534088
 100000_SF        2.965492      1.533928
 10000_10         1.533928      0.256005
 10000_20         3.059807      0.255988
 10000_5          0.770988      0.255959
 10000_SF         0.362581      0.253815
 1000_10          0.361370      0.249107
 1000_20          0.361858      0.249109
 1000_5           0.360332      0.245314
 1000_SF          0.356295      0.241580
 1015074_SBC     60.715370     15.496889
 ppi             18.720940      0.693420  ,
 'neo4jee_list': operation      create    delete     read_1       read_2        read_3  \
 dataset
 1000000_5    0.030011  0.016024  15.266838    58.137302     59.273326
 1000000_SF   0.030299  0.018643  15.266838  5911.049868  11876.727009
 100000_10    0.030157  0.016565   3.020216    12.360601     27.499121
 100000_20    0.030568  0.018643   5.951899    26.105709    207.442954
 100000_5     0.030566  0.018527   1.537674     6.065577      7.015989
 100000_SF    0.030326  0.017981   7.432526   448.078340   1227.364372
 10000_10     0.030421  0.018498   0.533231     2.153219     20.160783
 10000_20     0.030525  0.018498   0.982273     7.892103    287.876021
 10000_5      0.029852  0.016831   0.302307     0.913682      2.989484
 10000_SF     0.030360  0.018468  20.851974   340.541687    482.429482
 1000_10      0.030211  0.018083   0.273895     2.053632     12.488801
 1000_20      0.030316  0.018468   0.467094     6.902016     20.075634
 1000_5       0.029810  0.015880   0.172655     0.627911      2.794854
 1000_SF      0.029801  0.015550   6.971038    14.220146     14.145434
 1015074_SBC  0.030389  0.017675  15.496849    16.004866     15.710025
 ppi          0.030461  0.017476   4.807648    31.238860     58.109660

 operation    update_edges  update_nodes
 dataset
 1000000_5       76.301994     15.266874
 1000000_SF      30.786842     15.266838
 100000_10       15.266838      1.534042
 100000_20       30.525627      1.534088
 100000_5         7.637444      1.534088
 100000_SF        2.965492      1.533928
 10000_10         1.533928      0.252888
 10000_20         3.059807      0.252821
 10000_5          0.770988      0.250778
 10000_SF         0.362597      0.250802
 1000_10          0.361397      0.246114
 1000_20          0.361858      0.246085
 1000_5           0.360323      0.246047
 1000_SF          0.356328      0.238519
 1015074_SBC     60.715370     15.496964
 ppi             18.720940      0.693394  ,
 'postgres_col': operation      create    delete     read_1       read_2       read_3  \
 dataset
 1000000_5    0.053857  0.001704  15.266838    57.954587    58.430117
 1000000_SF   0.053679  0.002132  15.266838  1358.003492  2887.057439
 100000_10    0.053566  0.002089   2.940135    11.732799    13.328824
 100000_20    0.053613  0.001966   5.819043    23.679489    47.210145
 100000_5     0.053577  0.002060   1.533928     5.879369     6.112064
 100000_SF    0.053388  0.002100   1.813312   102.564480   285.465910
 10000_10     0.053342  0.002045   0.450363     1.297709    10.115623
 10000_20     0.053371  0.001988   0.842954     2.683016   281.979522
 10000_5      0.053309  0.002137   0.259579     0.732107     0.829672
 10000_SF     0.053056  0.002014  11.741322   333.956427   474.019614
 1000_10      0.052114  0.001692   0.110083     0.515597     4.234682
 1000_20      0.052993  0.001945   0.153823     1.612798     8.731108
 1000_5       0.052218  0.001822   0.085790     0.176989     0.691340
 1000_SF      0.039014  0.001706   1.690670     5.058586     5.634821
 1015074_SBC  0.039180  0.002064  15.496849    15.691401    15.691472
 ppi          0.039201  0.001896   4.034018    14.795811    33.444002

 operation    update_edges  update_nodes
 dataset
 1000000_5       76.302381     15.266989
 1000000_SF      30.786842     15.266998
 100000_10       15.267186      1.534126
 100000_20       30.525627      1.534245
 100000_5         7.637444      1.534213
 100000_SF        2.965492      1.534190
 10000_10         1.534155      0.160797
 10000_20         3.059807      0.160950
 10000_5          0.770988      0.160863
 10000_SF         0.281502      0.160952
 1000_10          0.160637      0.042437
 1000_20          0.313225      0.042574
 1000_5           0.084343      0.042437
 1000_SF          0.058517      0.041924
 1015074_SBC     60.715543     15.497047
 ppi             18.720940      0.693595  ,
 'postgres_list': operation      create    delete     read_1       read_2       read_3  \
 dataset
 1000000_5    0.053651  0.001717  15.266838    57.954023    58.429418
 1000000_SF   0.053590  0.002103  15.266838  1358.001365  2887.056686
 100000_10    0.053420  0.002103   2.937627    11.733450    13.328914
 100000_20    0.053437  0.001757   5.819212    23.678781    47.208873
 100000_5     0.053319  0.002152   1.533928     5.877084     6.110893
 100000_SF    0.053255  0.001996   1.811776   102.563506   285.463515
 10000_10     0.053285  0.002084   0.452443     1.297112    10.114284
 10000_20     0.053263  0.002030   0.842503     2.685377   281.978802
 10000_5      0.053188  0.002093   0.262698     0.730711     0.828513
 10000_SF     0.052932  0.002221  11.741695   333.956303   474.019185
 1000_10      0.052123  0.001982   0.109374     0.515922     4.233331
 1000_20      0.053002  0.001867   0.156351     1.612933     8.730510
 1000_5       0.052173  0.001700   0.085486     0.174288     0.689956
 1000_SF      0.039052  0.001706   1.690876     5.057629     5.634067
 1015074_SBC  0.038792  0.002123  15.496849    15.690164    15.689587
 ppi          0.039204  0.002101   4.032627    14.797879    33.441805

 operation    update_edges  update_nodes
 dataset
 1000000_5       76.302317     15.266998
 1000000_SF      30.786842     15.267139
 100000_10       15.266980      1.534154
 100000_20       30.525839      1.534222
 100000_5         7.637444      1.534126
 100000_SF        2.965732      1.534088
 10000_10         1.534101      0.160797
 10000_20         3.059807      0.160931
 10000_5          0.770988      0.160883
 10000_SF         0.281502      0.160797
 1000_10          0.160637      0.040741
 1000_20          0.313354      0.040875
 1000_5           0.084343      0.040701
 1000_SF          0.058517      0.040763
 1015074_SBC     60.715370     15.497009
 ppi             18.721113      0.693420  ,
 'sqlite_col': operation      create    delete     read_1       read_2       read_3  \
 dataset
 1000000_5    0.054437  0.000694  15.266838    57.937794    58.364552
 1000000_SF   0.054457  0.000697  15.266838  2734.522488  5526.626616
 100000_10    0.054437  0.000694   2.933273    11.689746    12.912446
 100000_20    0.054437  0.000694   5.811688    23.522490    79.249667
 100000_5     0.054430  0.000693   1.533928     5.858047     6.047102
 100000_SF    0.054450  0.000696   3.616196   207.907721   548.278847
 10000_10     0.054430  0.000693   0.447417     1.254990    10.109741
 10000_20     0.054430  0.000693   0.833434     3.666415   281.965598
 10000_5      0.054423  0.000692   0.253356     0.713762     1.391920
 10000_SF     0.054441  0.000695  11.735516   333.932900   473.992107
 1000_10      0.054423  0.000692   0.147696     1.003800     6.012058
 1000_20      0.054423  0.000692   0.236654     3.212685     8.747055
 1000_5       0.054421  0.000691   0.106244     0.309905     1.355349
 1000_SF      0.054437  0.000694   3.385565     6.559363     6.930287
 1015074_SBC  0.054511  0.000696  15.496849    15.693768    15.693593
 ppi          0.054301  0.000673   3.812389    13.239660    39.174740

 operation    update_edges  update_nodes
 dataset
 1000000_5       76.301994     15.266998
 1000000_SF      30.786842     15.266998
 100000_10       15.266838      1.534088
 100000_20       30.525627      1.534088
 100000_5         7.637444      1.534088
 100000_SF        2.965492      1.534088
 10000_10         1.533928      0.160797
 10000_20         3.059807      0.160797
 10000_5          0.770988      0.160797
 10000_SF         0.281502      0.160797
 1000_10          0.160637      0.038255
 1000_20          0.313225      0.038255
 1000_5           0.084343      0.038256
 1000_SF          0.058517      0.038406
 1015074_SBC     60.715370     15.497009
 ppi             18.720940      0.693420  ,
 'sqlite_list': operation      create    delete     read_1       read_2       read_3  \
 dataset
 1000000_5    0.054446  0.000701  15.266838    57.944147    58.368066
 1000000_SF   0.054466  0.000704  15.266838  1738.539801  3568.068079
 100000_10    0.054446  0.000701   2.934914    11.686112    12.914045
 100000_20    0.054446  0.000701   5.811159    23.524403    53.791073
 100000_5     0.054444  0.000700   1.533928     5.865442     6.051095
 100000_SF    0.054464  0.000703   2.318949   132.167399   350.310153
 10000_10     0.054445  0.000700   0.448889     1.251491    10.109741
 10000_20     0.054440  0.000700   0.832712     2.529042   281.964349
 10000_5      0.054438  0.000699   0.253094     0.724624     0.904259
 10000_SF     0.054453  0.000702  11.734383   333.932559   473.992039
 1000_10      0.054435  0.000699   0.113969     0.646831     4.248392
 1000_20      0.054434  0.000699   0.167667     2.059362     8.746298
 1000_5       0.054426  0.000698   0.088990     0.212815     0.877444
 1000_SF      0.054452  0.000701   2.170630     5.053923     5.630099
 1015074_SBC  0.054526  0.000703  15.496849    15.676541    15.675585
 ppi          0.054319  0.000680   3.810019    18.569924    48.887097

 operation    update_edges  update_nodes
 dataset
 1000000_5       76.301994     15.266998
 1000000_SF      30.786842     15.266998
 100000_10       15.266838      1.534088
 100000_20       30.525627      1.534088
 100000_5         7.637444      1.534088
 100000_SF        2.965492      1.534088
 10000_10         1.533928      0.160797
 10000_20         3.059807      0.160797
 10000_5          0.770988      0.160797
 10000_SF         0.281502      0.160797
 1000_10          0.160637      0.038275
 1000_20          0.313225      0.038265
 1000_5           0.084343      0.038264
 1000_SF          0.058517      0.038285
 1015074_SBC     60.715370     15.497000
 ppi             18.720940      0.693420  }